version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - /app/instance
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py
    command: flask run --host=0.0.0.0 --port=5001

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend    volumes:
      - ./frontend:/app
